project_id = "ddaybkxhpvlpvgnphahp"

[functions.telegram-bot]
verify_jwt = false

[functions.messenger-webhook]
verify_jwt = false

[functions.summarize-chat]
verify_jwt = false

[functions.capture-traffic]
verify_jwt = false

[functions.facebook-oauth]
verify_jwt = false
